### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by dalexandrov** [mminella/jsr352-springbatch-and-you#2]
Hello,
I'm trying to run your example on MacOS X and have the following issue:

/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/bin/java -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/mitia/Desktop/batch/jsr352-springbatch-and-you/target/classes:/Users/mitia/.m2/repository/org/springframework/spring-expression/3.2.0.RELEASE/spring-expression-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/org/springframework/spring-core/3.2.0.RELEASE/spring-core-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/mitia/.m2/repository/org/springframework/spring-aop/3.2.0.RELEASE/spring-aop-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/mitia/.m2/repository/org/springframework/spring-beans/3.2.0.RELEASE/spring-beans-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/org/springframework/spring-jdbc/3.2.0.RELEASE/spring-jdbc-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/org/springframework/spring-tx/3.2.0.RELEASE/spring-tx-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/org/springframework/spring-oxm/3.2.0.RELEASE/spring-oxm-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/commons-lang/commons-lang/2.5/commons-lang-2.5.jar:/Users/mitia/.m2/repository/org/springframework/batch/spring-batch-core/3.0.0.M2/spring-batch-core-3.0.0.M2.jar:/Users/mitia/.m2/repository/com/ibm/jbatch/com.ibm.jbatch-tck-spi/1.0/com.ibm.jbatch-tck-spi-1.0.jar:/Users/mitia/.m2/repository/javax/batch/javax.batch-api/1.0/javax.batch-api-1.0.jar:/Users/mitia/.m2/repository/com/thoughtworks/xstream/xstream/1.3/xstream-1.3.jar:/Users/mitia/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:/Users/mitia/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar:/Users/mitia/.m2/repository/org/springframework/spring-context/3.2.0.RELEASE/spring-context-3.2.0.RELEASE.jar:/Users/mitia/.m2/repository/org/springframework/batch/spring-batch-infrastructure/3.0.0.M2/spring-batch-infrastructure-3.0.0.M2.jar:/Users/mitia/.m2/repository/org/springframework/retry/spring-retry/1.0.2.RELEASE/spring-retry-1.0.2.RELEASE.jar:/Users/mitia/.m2/repository/commons-dbcp/commons-dbcp/1.2.2/commons-dbcp-1.2.2.jar:/Users/mitia/.m2/repository/commons-pool/commons-pool/1.3/commons-pool-1.3.jar:/Users/mitia/.m2/repository/org/slf4j/slf4j-log4j12/1.5.8/slf4j-log4j12-1.5.8.jar:/Users/mitia/.m2/repository/org/slf4j/slf4j-api/1.5.8/slf4j-api-1.5.8.jar:/Users/mitia/.m2/repository/log4j/log4j/1.2.14/log4j-1.2.14.jar:/Users/mitia/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar:/Users/mitia/.m2/repository/org/hsqldb/hsqldb/2.2.9/hsqldb-2.2.9.jar:/Users/mitia/.m2/repository/org/aspectj/aspectjrt/1.6.8/aspectjrt-1.6.8.jar:/Users/mitia/.m2/repository/org/aspectj/aspectjweaver/1.6.8/aspectjweaver-1.6.8.jar:/Users/mitia/.m2/repository/javax/inject/javax.inject-tck/1/javax.inject-tck-1.jar:/Users/mitia/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/mitia/.m2/repository/com/maxmind/geoip2/geoip2/0.4.1/geoip2-0.4.1.jar:/Users/mitia/.m2/repository/com/maxmind/maxminddb/maxminddb/0.2.0/maxminddb-0.2.0.jar:/Users/mitia/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar:/Users/mitia/.m2/repository/com/google/http-client/google-http-client/1.16.0-rc/google-http-client-1.16.0-rc.jar:/Users/mitia/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/mitia/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar:/Users/mitia/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar:/Users/mitia/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar:/Users/mitia/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar:/Users/mitia/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.0/jackson-databind-2.2.0.jar:/Users/mitia/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.2.0/jackson-annotations-2.2.0.jar:/Users/mitia/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.0/jackson-core-2.2.0.jar:/Users/mitia/.m2/repository/mysql/mysql-connector-java/5.1.26/mysql-connector-java-5.1.26.jar:/Users/mitia/.m2/repository/org/freemarker/freemarker/2.3.14/freemarker-2.3.14.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.springframework.batch.jsr.JsrMainClass logAnalysis inputFile=/Users/mitia/Desktop/swk_small.log stagingDirectory=/tmp/jsr_temp/out/
2015-06-09 11:43:07,206 INFO main [org.springframework.context.support.ClassPathXmlApplicationContext] - <Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@16b4a017: startup date [Tue Jun 09 11:43:07 EEST 2015]; root of context hierarchy>
2015-06-09 11:43:07,264 INFO main [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - <Loading XML bean definitions from URL [jar:file:/Users/mitia/.m2/repository/org/springframework/batch/spring-batch-core/3.0.0.M2/spring-batch-core-3.0.0.M2.jar!/beanRefContext.xml]>
2015-06-09 11:43:07,391 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1ed4004b: defining beans [baseContext]; root of factory hierarchy>
2015-06-09 11:43:07,455 INFO main [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - <Loading XML bean definitions from class path resource [baseContext.xml]>
2015-06-09 11:43:07,537 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Refreshing org.springframework.context.support.GenericXmlApplicationContext@37d31475: startup date [Tue Jun 09 11:43:07 EEST 2015]; root of context hierarchy>
2015-06-09 11:43:07,574 INFO main [org.springframework.beans.factory.config.PropertyPlaceholderConfigurer] - <Loading properties file from class path resource [batch-hsql.properties]>
2015-06-09 11:43:07,589 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1da51a35: defining beans [org.springframework.batch.core.scope.internalStepScope,org.springframework.beans.factory.config.CustomEditorConfigurer,org.springframework.batch.core.configuration.xml.CoreNamespacePostProcessor,batch_state_transition_comparator,jobRepository,jobLauncher,batchJobOperator,jobExplorer,dataSource,transactionManager,org.springframework.jdbc.datasource.init.DataSourceInitializer#0,jobParametersConverter,jobRegistry,placeholderProperties]; root of factory hierarchy>
2015-06-09 11:43:08,120 INFO main [org.springframework.batch.core.repository.support.JobRepositoryFactoryBean] - <No database type set, using meta data indicating: HSQL>
2015-06-09 11:43:08,268 INFO main [org.springframework.batch.core.launch.support.SimpleJobLauncher] - <No TaskExecutor has been set, defaulting to synchronous executor.>
2015-06-09 11:43:08,307 INFO main [org.springframework.jdbc.datasource.init.ResourceDatabasePopulator] - <Executing SQL script from class path resource [org/springframework/batch/core/schema-drop-hsqldb.sql]>
2015-06-09 11:43:08,308 INFO main [org.springframework.jdbc.datasource.init.ResourceDatabasePopulator] - <Done executing SQL script from class path resource [org/springframework/batch/core/schema-drop-hsqldb.sql] in 1 ms.>
2015-06-09 11:43:08,308 INFO main [org.springframework.jdbc.datasource.init.ResourceDatabasePopulator] - <Executing SQL script from class path resource [support/logEntry-hsql.sql]>
2015-06-09 11:43:08,316 INFO main [org.springframework.jdbc.datasource.init.ResourceDatabasePopulator] - <Done executing SQL script from class path resource [support/logEntry-hsql.sql] in 8 ms.>
2015-06-09 11:43:08,329 INFO main [org.springframework.beans.factory.xml.XmlBeanDefinitionReader] - <Loading XML bean definitions from class path resource [META-INF/batch-jobs/logAnalysis.xml]>
2015-06-09 11:43:08,347 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'logAnalysis': replacing [Generic bean: class [org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Generic bean: class [org.springframework.batch.core.jsr.configuration.xml.JobFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null]>
2015-06-09 11:43:08,349 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Refreshing org.springframework.context.support.GenericXmlApplicationContext@37d4349f: startup date [Tue Jun 09 11:43:08 EEST 2015]; parent: org.springframework.context.support.GenericXmlApplicationContext@37d31475>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'stepContextFactory': replacing [Generic bean: class [org.springframework.batch.core.jsr.StepContextFactoryBean]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'org.springframework.batch.jsr.batchlet.FileSplittingBatchlet': replacing [Generic bean: class [org.springframework.batch.jsr.batchlet.FileSplittingBatchlet]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'org.springframework.batch.jsr.chunk.LogReadingItemReader': replacing [Generic bean: class [org.springframework.batch.jsr.chunk.LogReadingItemReader]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'org.springframework.batch.jsr.chunk.GeocodingItemProcessor': replacing [Generic bean: class [org.springframework.batch.jsr.chunk.GeocodingItemProcessor]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'org.springframework.batch.jsr.chunk.LogEntryItemWriter': replacing [Generic bean: class [org.springframework.batch.jsr.chunk.LogEntryItemWriter]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,359 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Overriding bean definition for bean 'org.springframework.batch.jsr.batchlet.ReportBatchlet': replacing [Generic bean: class [org.springframework.batch.jsr.batchlet.ReportBatchlet]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in null]>
2015-06-09 11:43:08,362 INFO main [org.springframework.batch.core.jsr.configuration.support.JsrAutowiredAnnotationBeanPostProcessor] - <JSR-330 'javax.inject.Inject' annotation found and supported for autowiring>
2015-06-09 11:43:08,401 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'stepContextFactory' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,408 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'org.springframework.batch.jsr.batchlet.FileSplittingBatchlet' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,411 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'org.springframework.batch.jsr.chunk.LogReadingItemReader' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,414 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'org.springframework.batch.jsr.chunk.GeocodingItemProcessor' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,420 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'org.springframework.batch.jsr.chunk.LogEntryItemWriter' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,421 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'org.springframework.batch.jsr.batchlet.ReportBatchlet' of type [class org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,425 INFO main [org.springframework.context.support.GenericXmlApplicationContext] - <Bean 'batchPropertyContext' of type [class org.springframework.batch.core.jsr.configuration.support.BatchPropertyContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)>
2015-06-09 11:43:08,426 DEBUG main [org.springframework.batch.core.jsr.configuration.support.JsrAutowiredAnnotationBeanPostProcessor] - <Autowiring by type from bean name 'batchPropertyPostProcessor' to bean named 'batchPropertyContext'>
2015-06-09 11:43:08,428 INFO main [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@70e9c95d: defining beans [org.springframework.batch.core.scope.internalStepScope,org.springframework.beans.factory.config.CustomEditorConfigurer,org.springframework.batch.core.configuration.xml.CoreNamespacePostProcessor,batch_state_transition_comparator,batchPropertyPostProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,split,batchPropertyContext,jobProperties,import,report,logAnalysis,stepContextFactory,org.springframework.batch.jsr.batchlet.FileSplittingBatchlet,org.springframework.batch.jsr.chunk.LogReadingItemReader,org.springframework.batch.jsr.chunk.GeocodingItemProcessor,org.springframework.batch.jsr.chunk.LogEntryItemWriter,org.springframework.batch.jsr.batchlet.ReportBatchlet,scopedTarget.stepContextFactory,scopedTarget.org.springframework.batch.jsr.batchlet.FileSplittingBatchlet,scopedTarget.org.springframework.batch.jsr.chunk.LogReadingItemReader,scopedTarget.org.springframework.batch.jsr.chunk.GeocodingItemProcessor,scopedTarget.org.springframework.batch.jsr.chunk.LogEntryItemWriter,scopedTarget.org.springframework.batch.jsr.batchlet.ReportBatchlet]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@1da51a35>
2015-06-09 11:43:08,455 WARN main [org.springframework.beans.GenericTypeAwarePropertyDescriptor] - <Invalid JavaBean property 'tasklet' being accessed! Ambiguous write methods found next to actually used [public void org.springframework.batch.core.jsr.configuration.xml.StepFactoryBean.setTasklet(java.lang.Object)]: [public void org.springframework.batch.core.configuration.xml.StepParserStepFactoryBean.setTasklet(org.springframework.batch.core.step.tasklet.Tasklet)]>
Exception in thread "main" java.lang.IllegalArgumentException
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.asm.ClassReader.<init>(Unknown Source)
    at org.springframework.core.LocalVariableTableParameterNameDiscoverer.inspectClass(LocalVariableTableParameterNameDiscoverer.java:112)
    at org.springframework.core.LocalVariableTableParameterNameDiscoverer.getParameterNames(LocalVariableTableParameterNameDiscoverer.java:86)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:193)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1049)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:953)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:490)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
    at org.springframework.batch.core.jsr.launch.JsrJobOperator.start(JsrJobOperator.java:558)
    at org.springframework.batch.jsr.JsrMainClass.main(JsrMainClass.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1

**Comment by dalexandrov** [comment]
Moving to latest versions in maven and adding "batch.table.prefix=BATCH_" to DB properties files fixed everything.
